# Generated by Django 4.1.2 on 2022-10-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_stage_name'),
        ('albums', '0002_alter_album_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artists.artist'),
        ),
    ]
