# Generated by Django 4.1.1 on 2022-11-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
