# Generated by Django 4.1.1 on 2022-11-11 20:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_cost'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='album',
            managers=[
                ('approved_album', django.db.models.manager.Manager()),
            ],
        ),
    ]
