# Generated by Django 4.1.2 on 2022-10-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_at',
            field=models.DateTimeField(),
        ),
    ]
