# Generated by Django 4.1.1 on 2022-10-25 23:43

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterModelTable(
            name='album',
            table='albums',
        ),
        migrations.AlterModelTable(
            name='song',
            table='songs',
        ),
    ]
