# Generated by Django 4.1.1 on 2022-10-25 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_alter_song_image_thumbnail_alter_song_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='audio_file',
            new_name='audio',
        ),
    ]
